repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local

    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-duplicate-keys,
            --exclude=logs/models.py,
          ]

      # - id: reorder-python-imports
      #   name: reorder-python-imports
      #   entry: reorder-python-imports
      #   language: system
      #   types: [python]
      #   args: [--py37-plus]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--settings-path=./pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args: [--config=./.flake8]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        args: [./, --config=./pyproject.toml]
