version: '3.8'

services:
  app:
    image: ${PROD_IMAGE}
    container_name: flask-corporatica-app
    command: gunicorn --config gunicorn_config.py "app:create_app()"
    ports:
      - "8000:8000"
      - "3000:3000" # For debugging
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network

  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
