[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.mypy_cache
  | \.serverless
  | \.pytest_cache
  | \.tox
  | \.egg
  | \.eggs
  | \.cache
  | \.idea
  | \.vscode
  | \.mypy_cache
  | migrations
  | static
  | media
)/
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
profile = "django"
skip_glob = [
    ".git",
    ".venv",
    "*/migrations/*",
    "static",
    "media",
    ".cache",
    ".pytest_cache",
    ".vscode",
    ".idea",
    ".tox",
    ".egg",
    ".eggs",
    ".mypy_cache",
    ".serverless",
]


