"""Initial migration

Revision ID: 1687506a0bf8
Revises: 
Create Date: 2024-09-14 04:48:08.430493

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1687506a0bf8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tabular_data_files",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("statistics", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tabular_data_file_headers",
        sa.Column("tabular_data_file_id", sa.Integer(), nullable=False),
        sa.Column("header", sa.String(length=255), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tabular_data_file_id"],
            ["tabular_data_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tabular_data_file_rows",
        sa.Column("tabular_data_file_id", sa.Integer(), nullable=False),
        sa.Column("row_data", sa.JSON(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tabular_data_file_id"],
            ["tabular_data_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tabular_data_file_rows")
    op.drop_table("tabular_data_file_headers")
    op.drop_table("tabular_data_files")
    # ### end Alembic commands ###
