"""mask_type

Revision ID: 6751109624e3
Revises: 85ec884ce3fd
Create Date: 2024-09-15 02:32:34.493377

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6751109624e3"
down_revision = "85ec884ce3fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_masks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mask_type", sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_masks", schema=None) as batch_op:
        batch_op.drop_column("mask_type")

    # ### end Alembic commands ###
