"""image masks

Revision ID: 85ec884ce3fd
Revises: bff1ceeace11
Create Date: 2024-09-15 01:39:18.310603

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85ec884ce3fd"
down_revision = "bff1ceeace11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_masks",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("mask_data", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_masks")
    # ### end Alembic commands ###
