"""image thumpnail'


Revision ID: bff1ceeace11
Revises: d65f30c26e45
Create Date: 2024-09-15 00:11:21.534382

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bff1ceeace11"
down_revision = "d65f30c26e45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_data_file_thumbnails",
        sa.Column("image_data_file_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_data_file_id"],
            ["image_data_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("image_data_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("histogram", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_data_files", schema=None) as batch_op:
        batch_op.drop_column("histogram")

    op.drop_table("image_data_file_thumbnails")
    # ### end Alembic commands ###
